---
title: "Replication of The Zero-Sum Fallacy in Evidence Evaluation by Pilditch, Fenton and Lagnado (2019, Psychological Science)"
author: "Philip Hernandez (philipah@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->
## Repository
[Github repository](https://github.com/psych251/pilditch2019)

## Experimental Paradigm

[Qualtrics Survey](https://stanforduniversity.qualtrics.com/jfe/form/SV_2gK1VSf5qoa1q7z)

## Original Paper

[Pilditch, Fenton, and Lagnado (2019)](https://github.com/psych251/pilditch2019/tree/master/original_paper/pilditch2019.pdf "pilditch2019")

##Introduction
My research interests lie in studying adult learning in the sciences, from the undergraduate sciences through medical school, especially where learning still takes place in lecture halls. However, I’m also interested in what neuroscience and the cognitive sciences can bring to this realm and what can be learned using these populations of post-secondary students. This study, though nominally part of this body of research does concern itself with the population I am interested in.  In addition, I feel that in replicating this study, I would not only be able to hone skills necessary for processing data, but also explore an area of interest in my work. I find the underlying idea of the zero-sum fallacy something to be considered in educational assessment, even if the study is far removed from application in the classroom setting.   

The study was originally performed using mTurk in three related experiments in which scenarios were described onscreen after which respondents answered questions indicating whether their judgment was "yes", "no", or "Cannot Tell". The main difficulties would lie in recruiting, screening, and paying a large enough sample size- 25 people for experiment 1, 200 each in experiments 2 and 3. Beyond randomly assigning participants to groups and the experiment stimulus does not require specialized programming in mTurk. Storage, retrieval and analysis would pose a challenge, as I am not yet familiar with data storage and output from mTurk. As we seek to replicate only one experiment, I would be able to  



##Methods

###Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

###Planned Sample

Until power analysis is completed, planned sample will mirror that described in Experiment 2. 200 subjects will be recruited from a US-based native English speaker population in MTurk. 

###Materials

Materials from experiment will be used as indicated in Experiment 2 of Pilditch (2019) quoted below. 

"Each participant was assigned to
one of two conditions: Either all scenarios contained positive
test results or all contained negative test results. In all
cases, there was both a target and an alternative explanation
for the test result ...


"... To address the exhaustiveness
issue, we introduced a between-subjects factor,
in which an explicit statement regarding non-exhaustiveness
was either present (non-exhaustiveness statement) or
absent (control). This, in conjunction with the test-result
between-subjects manipulation, led to a 2 × 2 design. The
non-exhaustiveness statement preceded the standard
judgment question and used the following structure:
“Please note, it is possible that [subject] neither [Hypothesis
1] nor [Hypothesis 2].”

"To address the confidence question, we included a
confidence measure directly below the judgment
question: “How confident are you that your response
is correct?” Participants responded using a slider to
indicate from 0% to 100% (no default value; for an
example scenario, see Section C of the Supplemental
Material)."






###Procedure	

Procedures of experiment will be used as indicated in Experiment 2 of Pilditch (2019) quoted below.

"Participants completed basic
demographics (age, gender, native language) before moving
on to the scenarios. Each participant completed the
four scenarios ...
in a random order."

"For each scenario, participants were asked to make a judgment
of “yes,” “no,” or “cannot tell” when posed with the
following example format: “Does a [positive/negative] Griess
test result give any support to the claim that Ann [has/has
not] handled explosives?”

"On a separate page, after each scenario judgment,
participants were asked to “please briefly provide some
reasoning for your decision regarding the previous scenario
in the text box below” (not reported in this article).
Along with demographics, scenario order and time taken
were recorded."

"Accordingly, as participants completed each
of the four scenarios in random order, they made a
judgment, expressed their confidence in that judgment,
and then provided some reasoning."

###Analysis Plan

Data tables will include participant demographics, experimental conditions(order, positive/negative results, control/non-exhaustive statement), participant responses, time to respond, participant confidence ratings, and participant explanations.

Mirroring the analysis done in Pilditch(2019), I plan on conducting "a Bayesian analysis of variance (ANOVA) with test result and exhaustiveness manipulation (both between subjects)" as this will test the main inference of the paper. For this, only the participant responses (correct vs. incorrect) and experimental conditions will be used. 

To further examine relationships, a 3(responses) x 2 (test condition positive/neg ) x 2 (knowledge of exhaustiveness/control) ANOVA will be conducted. 
  


###Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


##Results


### Data preparation

Data preparation following the analysis plan.

Libraries to be used: 

library(tidyr)
library(dplyr)
library(stringr) 
library(ggplot2)
library(readxl)

Data will be imported from Qualtrics via mTurk survey, extraneous data discarded and converted to long format from wide format for each of the analysis. 


```{r include=F, }
###Data Preparation


####Load Relevant Libraries and Functions
library(tidyr)
library(dplyr)
library(stringr) 
library(ggplot2)
library(readxl)

####Import data

pilot <- read_xlsx('https://github.com/psych251/pilditch2019/blob/master/Pilot_data_revised.xlsx')

#### Data exclusion / filtering

pilot_rows12_removed <- pilot[-c(1,2),]

filtered_pilot <- select(pilot_rows12_removed, +contains("Nitro"), +contains("Ster"), +contains("BT"), +contains("Crash")) #remove extra qualtrics columns

exp2_filtered <- select(filtered_pilot, -contains("rn")) #remove reasoning for choice 

exp2_decision <- select(exp2_filtered, -contains("%")) # only decisions retained



# group data by condition, find mean porportions of each condition

#Analyis 1



#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan. 

#### Judgement Analysis
Means of porportions will be computed by grouping by test-result condition (variable defined as positive or negative) and further by control and Non-exhaustive Statement (variable defined as control_exhaustive and exp_N_exhaustive). 


#### ANOVA Analysis

A Bayesian Analysis of Variance will be completed looking at test result (positive/negative) and presence of non-exhaustive statement (control_exhaustive and exp_N_exhaustive).


#### Confidence Analysis

Means of confidence in judgments will be computed by grouping by test-result condition (variable defined as positive or negative) and further by control and Non-exhaustive Statement (variable defined as control_exhaustive and exp_N_exhaustive).Graph will be displayed as a box and whisker plot. 


*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.

